# permissions for end users to view livekitmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: livekitmesh-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: livekit-operator
    app.kubernetes.io/part-of: livekit-operator
    app.kubernetes.io/managed-by: kustomize
  name: livekitmesh-viewer-role
rules:
- apiGroups:
  - livekit.stunner.l7mp.io
  resources:
  - livekitmeshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - livekit.stunner.l7mp.io
  resources:
  - livekitmeshes/status
  verbs:
  - get
