---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - livekit.stunner.l7mp.io.l7mp.io
  resources:
  - livekitmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - livekit.stunner.l7mp.io.l7mp.io
  resources:
  - livekitmeshes/finalizers
  verbs:
  - update
- apiGroups:
  - livekit.stunner.l7mp.io.l7mp.io
  resources:
  - livekitmeshes/status
  verbs:
  - get
  - patch
  - update
