apiVersion: livekit.stunner.l7mp.io.l7mp.io/v1alpha1
kind: LiveKitMesh
metadata:
  labels:
    app.kubernetes.io/name: livekitmesh
    app.kubernetes.io/instance: livekitmesh-sample
    app.kubernetes.io/part-of: livekit-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: livekit-operator
  name: livekitmesh-sample
  namespace: default
spec:
  components:
    liveKit:
      deployment:
        replicas: 1 #opt
        config:
          keys:
            access_token: secretsecretsecretsecretsecretsecret
          log_level: debug
          port: 7880
          redis:
            address: redis.default.svc:6379
          rtc:
            port_range_end: 60000
            port_range_start: 50000
            tcp_port: 7801
            turn_servers:
              - uri: http://stunner-auth.stunner-gateway-system.svc:8088?service=turn
            use_external_ip: false
#        configMap:
#          namespace: default
#          name: default-livekit-config
        # container template
        container:
          image: davidkornel/livekit-patched:latest
          imagePullPolicy: Always
          args: ["--disable-strict-config"]
          #          command: # TODO
          #          env: # TODO
          terminationGracePeriodSeconds: 3600
          #          affinity: # TODO
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
    certManager:
      issuer:
        apiToken: dummytoken
        challengeSolver: cloudflare
        dnsZone: example.com
        email: dummy@dummy.com
#    gateway:
#      relatedStunnerGatewayAnnotations:
#        name: udp-gateway
#        namespace: stunner-gateway-system
#      service:
  #        name: lk-control
  #        type: LoadBalancer
  #        ports:
  #          - port: 1
  #            protocol: TCP
  #          - port: 2
  #            protocol: TCP
  #
  #
  #
  #
  #
  #
  #    scaling:
  #    #TODO
  #    ingress:
  #    #TODO
  #    egress:
  #    #TODO

  #    monitoring:
  #    #TODO
