apiVersion: livekit.stunner.l7mp.io.l7mp.io/v1alpha1
kind: LiveKitOperator
metadata:
  annotations:

  #copy crd's annotations to final deployment
  labels:
    app.kubernetes.io/name: livekitoperator
    app.kubernetes.io/instance: livekitoperator-sample
    app.kubernetes.io/part-of: livekit-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: livekit-operator
  name: livekitoperator-sample
spec:
  components:
    mediaServer:
      type: livekit
      deployment:
        replicas: 2 #opt
        # container template
        container:
          image: dummy-repo/dummy-image:dummy-tag
          pullPolicy: IfNotPresent
          args: # TODO
          command: # TODO
          env: # TODO
          terminationGracePeriod: 3600
          affinity: # TODO
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
        config:
          # access_token must be at least 32 chars long
          keys:
            access_token: secretsecretsecretsecretsecretsecret
          log_level: info
          port: 7880
          redis:
            address: redis.default.svc:6379
          rtc:
            port_range_end: 60000
            port_range_start: 50000
            tcp_port: 7801
            stun_servers:
              - stunner_ip:3478
            turn_servers:
              - credential: pass-1
                host: stunner_ip
                port: 3478
                protocol: udp
                username: user-1
            use_external_ip: false
          turn:
            enabled: false
            loadBalancerAnnotations: {}

      service:
        namespace: dummy
        type: LoadBalancer
        ports:
          - port: 1
            protocol: TCP
          - port: 2
            protocol: TCP






    scaling:
    #TODO
    ingress:
    #TODO
    egress:
    #TODO
    certManager:
    #TODO
    monitoring:
    #TODO