apiVersion: livekit.stunner.l7mp.io.l7mp.io/v1alpha1
kind: LiveKitMesh
metadata:
  labels:
    app.kubernetes.io/name: livekitmesh
    app.kubernetes.io/instance: livekitmesh-sample
    app.kubernetes.io/part-of: livekit-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: livekit-operator
  name: livekitmesh-sample
spec:
  components:
    liveKit:
      deployment:
        replicas: 2 #opt
        # container template
        container:
          image: dummy-repo/dummy-image:dummy-tag
          imagePullPolicy: IfNotPresent
          #          args: # TODO
          #          command: # TODO
          #          env: # TODO
          #          terminationGracePeriodSeconds: 3600
          #          affinity: # TODO
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
#      service:
  #        name: lk-control
  #        type: LoadBalancer
  #        ports:
  #          - port: 1
  #            protocol: TCP
  #          - port: 2
  #            protocol: TCP
  #
  #
  #
  #
  #
  #
  #    scaling:
  #    #TODO
  #    ingress:
  #    #TODO
  #    egress:
  #    #TODO
  #    certManager:
  #    #TODO
  #    monitoring:
  #    #TODO
