apiVersion: livekit.stunner.l7mp.io.l7mp.io/v1alpha1
kind: LiveKitMesh
metadata:
  labels:
    app.kubernetes.io/name: livekitmesh
    app.kubernetes.io/instance: livekitmesh-sample
    app.kubernetes.io/part-of: livekit-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: livekit-operator
  name: livekitmesh-sample
  namespace: default
spec:
  components:
    liveKit:
      deployment:
        replicas: 2 #opt
        configMap:
          namespace: default
          name: default-livekit-config
#          name: default-livekit-config
#          namespace: default
        # container template
        container:
          image: livekit/livekit-server:v1.4.2
          imagePullPolicy: IfNotPresent
          args: ["--disable-strict-config"]
          #          command: # TODO
          #          env: # TODO
          terminationGracePeriodSeconds: 3600
          #          affinity: # TODO
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
    gateway:
      relatedStunnerGatewayAnnotations:
        name: udp-gateway
        namespace: stunner-gateway-system
#      service:
  #        name: lk-control
  #        type: LoadBalancer
  #        ports:
  #          - port: 1
  #            protocol: TCP
  #          - port: 2
  #            protocol: TCP
  #
  #
  #
  #
  #
  #
  #    scaling:
  #    #TODO
  #    ingress:
  #    #TODO
  #    egress:
  #    #TODO
  #    certManager:
  #    #TODO
  #    monitoring:
  #    #TODO
