apiVersion: v2
name: livekit-operator
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: cert-manager
    version: 1.14.5
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
  - name: stunner-gateway-operator
    version: 0.18.0
    repository: https://l7mp.io/stunner
    alias: stunner-gateway-operator
    condition: stunner-gateway-operator.enabled
  - name: gateway-helm
    version: v1.0.1
    repository: oci://registry-1.docker.io/envoyproxy
    alias: envoy-gateway
    condition: envoy-gateway.enabled

keywords:
  - kubernetes
  - operator
  - webrtc
  - media-server
  - livekit
  - stunner
  - envoy-gateway
  - gateway-api

maintainers:
  - name: Kornel David
    email: konel1020@gmail.com
  - name: l7mp
    url: l7mp.io